# Site settings
title: Dave's Blog
email: dave@harris.org.nz
description:
baseurl: ""
url: http://daveharris.github.io

# Build settings
markdown: redcarpet

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"